# Generated by Django 3.2.7 on 2021-10-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_rbaccontentguard'),
    ]

    operations = [
    ]
