# Generated by Django 3.2.7 on 2021-10-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_reserved_resource'),
        ('core', '0077_bmbouter_test'),
    ]

    operations = [
    ]
